name: Cleaning comma

on:
  workflow_run:
    workflows: ["CSV to XML for mtd Artefacts"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 1.8
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'
       - name: Clone project-doc with Ant
         run: ant -noinput -buildfile clone-projectDoc.xml

       - name: run xslt to clean comma with java in command lines - artefacts
         run: java -jar ./project-documentation/editorialStylesheets/pipelineTools/saxon9he.jar -s:./temporary/mdt_artefacts.xml -xsl:./project-documentation/stylesheets/mdt_inscriptions/mdt_CommaCleaning.xsl -o:./temporary/mdt_artefacts.xml

       - name: run xslt to clean comma with java in command lines - conglomerate artefacts
         run: java -jar ./project-documentation/editorialStylesheets/pipelineTools/saxon9he.jar -s:./temporary/mdt_conglomerate-artefacts.xml -xsl:./project-documentation/stylesheets/mdt_inscriptions/mdt_CommaCleaning.xsl -o:./temporary/mdt_conglomerate-artefacts.xml

       - name: Updating the cleaned files
         run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add temporary/
          git commit -m "Cleaning comma has been successfully done"
          git push
